# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Downloading SCA Resolver
    curl -L https://sca-downloads.s3.amazonaws.com/cli/1.14.2/ScaResolver-linux64.tar.gz -o ScaResolver-linux64.tar.gz
    tar -xvf ScaResolver-linux64.tar.gz
    rm ScaResolver-linux64.tar.gz
    chmod +x ScaResolver
    ls -l
    #mvn -version
    pwd
    docker ps
    echo Agent.BuildDirectory $(Agent.BuildDirectory) 
    echo Build.Repository.LocalPath $(Build.Repository.LocalPath) 
    echo Build.SourcesDirectory $(Build.SourcesDirectory) 
    echo Build.DefinitionName $(Build.DefinitionName) 
    echo Build.Repository.Name $(Build.Repository.Name) 
    echo Build.SourceBranch $(Build.SourceBranch) 
    echo Build.SourceBranchName $(Build.SourceBranchName) 
    echo System.JobName $(System.JobName) 
    ./ScaResolver -s $(Build.Repository.LocalPath) -n WebGoat -a BP -u $(scaUsername) -p $(scaPassword) --server-url https://eu.api-sca.checkmarx.net --authentication-server-url https://eu.platform.checkmarx.net --sca-app-url https://eu.sca.checkmarx.net --log-level Debug --save-evidence-path ./evidences.json --extract-archives zip,ear --extract-depth 3 --gradle-exclude-scopes api,testCompile --project-tags foo:bar dog:cat RepoID:1b1e417c-68dd-454b-b19f-37f7b371178f\;1b1e417c-68dd-454b-b19f-37f7b371178f --bypass-exitcode --cxserver https://sast.bpglobal.com --cxuser $username --cxpassword $password --cxprojectname WebGoat
    
#  displayName: 'SCA Resolver download'

#- task: Application security testing@2022
  #continueOnError: true
  #inputs:
    #projectName: 'WebGoat'
    #enableProxy: false
    #enableSastScan: false
    #enableDependencyScan: true
    #dependencyServerURL: 'CxSCA'
    #scaTeam: 'CxServer/test'
    #isEnableScaResolver: true
    #pathToScaResolver: '$(Build.Repository.LocalPath)'
    #scaResolverAddParameters: '-s $(Build.Repository.LocalPath) -n WebGoat -r $(Build.Repository.LocalPath) --cxserver https://sast.bpglobal.com --cxuser $username --cxpassword $password --cxprojectname WebGoat --sast-result-path $(Build.Repository.LocalPath)/lgv.txt'
    #scaResolverAddParameters: '-s $(Build.Repository.LocalPath) -n WebGoat -r $(Build.Repository.LocalPath) --scan-tags foo=bar'



- script: |
    echo SCA Resolver Logs
    ls -al logs
    cat logs/*/*
  displayName: 'SCA Resolver Logs'