# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: CxFlowPoc
- name: vsastUrl
  value: $[variables.sastUrl] 
- name: vsastUsername
  value: $[variables.sastUsername] 
- name: vsastPassword
  value: $[variables.sastPassword] 
#- name: vADO_PAT
#  value: $[variables.ADO_PAT] 

stages:
- stage: Security
  jobs:
  - job: CxFlow
    steps:
    - task: CmdLine@2
      inputs:
        script: |
            wget -O cxflow.jar https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.19/cx-flow-1.6.19.jar
            java -version
            whoami
            pwd 
            echo $(vsastUrl)
            echo $(vsastUsername)
            echo $(vsastPassword)
            #echo $(vADO_PAT)
            #java -jar cxflow.jar --spring.config.location="./application_ADO_Powershell.yml" --project  --cx-project="LGV_OneFile_ADO_CxFlow" --alt-project="LGV_OneFile_ADO_CxFlow" --namespace="$(System.TeamProject)" --repo-name="$(Build.Repository.Name)" --branch="$(Build.SourceBranchName)"
            # Reference https://github.com/checkmarx-ltd/cx-flow/wiki/Execution#command
            java -jar cxflow.jar \
                   --spring.config.location="$(Build.Repository.LocalPath)/app_sca.yml"  \
                   --scan \
                   --f=. \
                   --cx-project="Cx-$(System.TeamProject)" \
                   --exclude-files="*.jar" \
                   --alt-project="$(System.TeamProject)" \
                   --namespace="MichaelMatias" \
                   --repo-name="$(Build.Repository.Name)" \
                   --branch="$(Build.SourceBranchName)" \
                   --cxflow.enabled-vulnerability-scanners=sast \
                   --checkmarx.base-url=$(vsastUrl) \
                   --checkmarx.username=$(vsastUsername) \
                   --checkmarx.password=$(vsastPassword) \
                   #--azure.token=$(vADO_PAT) \
                   --cxflow.bug-tracker-impl=Azure \
                   --cxflow.bug-tracker=Azure
